### ISSUE TITLE
merge and autograde runs for incorrect number of arguments

### ISSUE THREAD

**Issue by rohansapre** [bharat94/Git-AI-Grader#2]
When the following command `./merge-and-autograde.sh` is executed which is actually short of one argument to run correctly, the program still runs and doesn't terminate after displaying the correct usage. One simple solution is to exit with an error after displaying the correct usage.

**Comment by rohansapre** [comment]
@bharat94 Will submit a PR for this soon!

**Comment by bharat94** [comment]
Could you address the changes mentioned?

**Comment by rohansapre** [comment]
Sure on it.
